name: CategoriesWithAmbientObjects
version: "2021.10-01"
license: "GPL-2.0-or-later"
date: 2021-10-26
description: |
    Categories with objects having ambient objects

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

GAP: ">=4.4"

needed-pkgs:
    - name: "AutoDoc"
      version: ">= 2013.12.04"
      url: "https://gap-packages.github.io/AutoDoc"
    - name: "AttributeCategoryForCAP"
      version: ">= 2016.09.14"
      url: "https://homalg-project.github.io/pkg/AttributeCategoryForCAP"
    - name: "GeneralizedMorphismsForCAP"
      version: ">= 2017.04.01"
      url: "https://homalg-project.github.io/pkg/GeneralizedMorphismsForCAP"
    - name: "FreydCategoriesForCAP"
      version: ">= 2020.09-21"
      url: "https://homalg-project.github.io/pkg/FreydCategoriesForCAP"
    - name: "ToolsForHomalg"
      version: ">= 2015.09.23"
      url: "https://homalg-project.github.io/pkg/ToolsForHomalg"
    - name: "GAPDoc"
      version: ">= 1.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://homalg-project.github.io/pkg/CategoriesWithAmbientObjects
readme: README.md
packageinfo: https://homalg-project.github.io/CategoriesWithAmbientObjects/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/CategoriesWithAmbientObjects/releases/download/v2021.10-01/CategoriesWithAmbientObjects-2021.10-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/CategoriesWithAmbientObjects/releases/download/v2021.10-01/CategoriesWithAmbientObjects-2021.10-01.zip

pdf: https://github.com/homalg-project/CategoriesWithAmbientObjects/releases/download/v2021.10-01/CategoriesWithAmbientObjects-2021.10-01.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    categories, ambient objects.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BS21</span>]   <b class='BibAuthor'>Barakat, M. and Saleh, K.</b>,
     <i class='BibTitle'>CategoriesWithAmbientObjects, Categories with objects having ambient objects,
             Version 2021.10-01</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/CategoriesWithAmbientObjects">https://homalg-project.github.io/pkg/CategoriesWithAmbientObjects</a></span>.
    </p>
    

bibtex: |
    @misc{ CategoriesWithAmbientObjects2021.10-01,
      author =           {Barakat, M. and Saleh, K.},
      title =            {{CategoriesWithAmbientObjects},     Categories    with
                          objects having ambient objects, {V}ersion 2021.10-01},
      month =            {Oct},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/CategoriesWithAmbientObjects}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{CategoriesWithAmbientObjects}}},
      keywords =         {categories; ambient objects},
      printedkey =       {BS21}
    }

